### ISSUE TITLE
Convert to the HTML5 boilerplate

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#10]
It's just great front end boilerplate code.

It won't affect the our code very much, so this shouldn't take much work. 

I'd also like to use their build script which will compress images, minify JS and do a ton of other magic on the fly.

https://github.com/h5bp/html5-boilerplate

**Comment by bheesham** [comment]
Hmmm... I took a look at the repo and was just put off by all the files we wouldn't need.
It also seems as though there's a lot of CSS rules that we won't end up touching.

If you can justify using it, then yeah sure, but it seems as though this is a shotgun approach.

**Comment by cdelahousse** [comment]
We're not expected to use it all. We can use it piece meal. Hell, I'd be happy just copy pasting bits of code from the project. 

Every part of the project is supposed to give you a really good starting point, plus a few other goodies. The index.html page uses a ton of cool little tricks. The CSS gives a browser normalized base (defaults) to build from and a ton of helper classes, such as the clear fix and accessibility hacks.

Again, I don't want to use all of it, I just want to port the better, more applicable bits.

**Comment by spratt** [comment]
We should meet up and talk about this.  I think @cdelahousse  can make his case on the parts he thinks we should use.

Our CSS needs a serious overhaul and we aren't following any best practices for anything to my knowledge, so I think there's a target rich environment for improving things.

**Comment by spratt** [comment]
I think we've decided not to do this in general, but we can copy in any specific elements that seem like a good idea.
