### ISSUE TITLE
Include Steamed-Pears-docs as a git submodule

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#106]
I don't know how to do this, and I suspect either @bheesham @cdelahousse or @psimonyi does.  :)

**Comment by psimonyi** [comment]
Well, I started reading about this, and it seems submodules aren't as great as they appear: they do what we want, but you have to be careful and run a ridiculous number of git commands every time you do something. And submodules aren't even cloned as part of the containing repository :( so it seems like a net disadvantage to make the docs a submodule while we're still working on them.
