### ISSUE TITLE
r.js breaks Code Review

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#109]
I've finished a first draft of our build script (see bin/build_production_all.sh on the build-production branch of my personal repo https://github.com/cdelahousse/Steamed-Pears/tree/build-production ).

Unfortunately, minifying using the r.js optimization script seems to be breaking the `main.js` script on the client side. 

I'm testing the production build by cloning a clean copy of Code Review and replacing the contents of `src/client` with that from the production script output. This allows me to serve the production build on my local machine.

Anyways, everything is getting served fine, but when I'm getting a JS error.

```
  Uncaught TypeError: Cannot call method 'fromTextArea' of undefined main.js:114
  n.codeFromTextArea       main.js:114
  i.init       main.js:114
  (anonymous function)       main.js:114
  x.execCb       require.js:7
  S.check       require.js:7
  S.enable       require.js:7
  S.init       require.js:7
  (anonymous function)       require.js:7
```

I've got to go easter supper, so I can't test it a bit more tonight. I suppose the issue is from uglifyjs. `r.js` uses uglify to minify the scripts. Later, I'm going to disable minification and see if the problem persists.

In the meantime, @spratt, could you check out my modifications to app.build.js in the client scripts folder and see if everything is in check? Maybe I fucked up in the build profile.

**Comment by spratt** [comment]
It may be from uglifyjs.  We can test it if we can get r.js to concatenate the files without minifying.  I'll see what I can figure out.

**Comment by cdelahousse** [comment]
Yeah. I'm pretty sure its uglify. There are options to change to the closure compiler but that may incure a java dependence. I'll try that when I have a moment.

**Comment by psimonyi** [comment]
It may not be. Not all the "modules" in the client are using require.js
properly, and that might confuse the optimizer. I was reading the
Require docs recently, and it seems there are some fairly significant
differences from CommonJS modules. Basically, each client-side file
should be one big call to define().

**Comment by spratt** [comment]
Remember that all the code mirror syntax highlighting files will need to be added separately because they are loaded dynamically by a string value rather than a parseable string.

**Comment by spratt** [comment]
Alright, I turned optimization off...but when your script says that it builds to the production directory, there are a lot of missing files in that directory.

**Comment by spratt** [comment]
Figured out the problem (see https://github.com/cdelahousse/Steamed-Pears/commit/8e7a6d1a3897e4ecc1bbd06f0a142c114f9d3279 for discussion).  With uglify turned off, it doesn't run.  It can't find CodeMirror.

**Comment by spratt** [comment]
Alright, I have it fixed without minification.  See https://github.com/spratt/Steamed-Pears/commit/1a6d10f16020c48f77529be2fcba22ce98b42d3a

The problem was that the runtime has a lot of what require.js calls "shims" which addresses the problem that @psimonyi was talking about.  Namely, not all of our libraries play nicely as require.js modules.  So require.js needs a little extra configuration to understand what the module should export.

**Comment by spratt** [comment]
After adding uglifyJS back in, it still works fine.  https://github.com/spratt/Steamed-Pears/commit/aea31c908fc2e8b0eef75c6d39b6958b4e0f9408

**Comment by spratt** [comment]
It bugged me that we had to duplicate a lot of the configuration we're doing for the runtime.  Turns out, require.js can just read in the runtime configuration and use that.  See https://github.com/spratt/Steamed-Pears/commit/bc1366a35e49f5903e8de4a932a2df31b9957b23
