### ISSUE TITLE
Update Server API on wiki

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#119]
#116 has us referring to the the Server API on the wiki. I think it's a bit out of date. It should be updated.

**Comment by spratt** [comment]
#116 doesn't refer to the Server API on the wiki that I can see.

**Comment by cdelahousse** [comment]
The solution to #116 will have a reference to all existing documentation. The server API is part of the existing docs.

**Comment by spratt** [comment]
We decided that the server API was really supposed to be kept as a file in the repo.  See https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears/wiki/Process

**Comment by cdelahousse** [comment]
Can we start doing this after we've delivered the project? Let's focus on shipping.

**Comment by spratt** [comment]
I think we can ship and write a server API doc.

**Comment by cdelahousse** [comment]
The API doc has already been written. It just needs to be updated.

There's problem, though. The API docs, according to our process document, should be located in the `docs` folder. That's where Anil's required docs will go. I don't want to confuse him by popultating that directory with non essential files.

Let's just keep it the wiki for now.

**Comment by spratt** [comment]
The API doc can be updated in text format.

We'll have to modify the location of the text file.

Let's stick to the agreement we came to at the start of the project.

**Comment by spratt** [comment]
https://github.com/spratt/Steamed-Pears/blob/personaServer/http_api.md

**Comment by spratt** [comment]
Sorry.  I'll close when the pull request gets accepted.

**Comment by psimonyi** [comment]
Closed by #111
