### ISSUE TITLE
Architecture Doc

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#120]
It's a required doc. @bheesham or @spratt, use your tablet to draw another diagram. We'll need to delete the one in the wiki.

**Comment by spratt** [comment]
Why do we need to delete the one on the wiki?

**Comment by cdelahousse** [comment]
It's out of date. We don't use sequelize, formidable, etc...

**Comment by psimonyi** [comment]
@cdelahousse put one in the docs submodule.
