### ISSUE TITLE
Easy Developer Deployment

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#13]
A requirement is for it to be as easy as possible for a new member like @psimonyi or a TA like @jbeltram to pull down the repo and run our code.

Since I have experience deploying the code on our production server and several dev servers, I'll take lead in making this happen.

**Comment by cdelahousse** [comment]
Sounds as awesome as cheese on bacon.

**Comment by spratt** [comment]
Update: I have nice scripts for starting and stopping the server in dev mode.  All that's left to do now is the dev mode of the database, for which we'll use sqlite since it's super simple and good enough for a development environment.

**Comment by spratt** [comment]
The ORM will be generating the SQL.  It should handle the variations, but I agree - be alert.

**Comment by spratt** [comment]
So the persistencejs ORM won't install and apparently hasn't worked since node 0.5 (!!).  I'll make a pull request with the version that works except for the DB and if anyone feels like taking a crack at making it easy to deploy, they are welcome.  I'm switching over to 4804 studying.

**Comment by spratt** [comment]
Turned out, the ORM we were using before (sequelize) supports sqlite with only minor tweaking.

**Comment by spratt** [comment]
Resolved by f92859798a4c67c49d96c3aa5a6df2a3e38797ac
