### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#154]
See: http://review.steamedpears.com

**Comment by spratt** [comment]
Specifically, see what happens when you try to load a piece of code that already exists.  e.g. http://review.steamedpears.com/index.html?id=f9ff145f-4d64-49c0-9269-ceaba53efdc7

**Comment by spratt** [comment]
This is fixed on a commit waiting to be pulled into Bhee's commit.

**Comment by psimonyi** [comment]
Fixed by f6c9cdd in #126.
