### ISSUE TITLE
Build script broken

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#161]
Turns out the build script didn't work, but it failed silently.  See the 403 at http://review.steamedpears.com/

The line that runs mktemp uses an option that doesn't exist on the production version.  I'm fixing now.

**Comment by spratt** [comment]
I replaced the --tmp-dir option with -t, which fixes the problem.  Pull request will come later.

**Comment by spratt** [comment]
Ugh... -t is deprecated in my local version of mktemp, but it's the only thing that works on the server.

**Comment by spratt** [comment]
On server:

```
[sdp@sdp.com ~]$ mktemp -V
mktemp version 1.5
```

On lab computer:

```
spratt@bernoulli:~$ mktemp --version
mktemp (GNU coreutils) 7.4
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering
```

**Comment by psimonyi** [comment]
At home:

```
[psimonyi@frederick ~]$ mktemp --version
mktemp (GNU coreutils) 8.17
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Eric Blake.
```

I still have `-t` (and it's still deprecated). "Unlike with -t, TEMPLATE [in --tmpdir=TEMPLATE] may contain slashes[...]", so `-t` should be fine until it disappears.

**Comment by spratt** [comment]
On my mac:

```
spratt@europa ~$ mktemp
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

The only version information I have is in the man page:

```
HISTORY
     A mktemp utility appeared in OpenBSD 2.1.  This implementation was writ-
     ten independently based on the OpenBSD man page, and first appeared in
     FreeBSD 2.2.7.  This man page is taken from OpenBSD.
```

I think the reason BSD doesn't include --version is because BSD considers all these programs to be part of the operating system, so the version is just the version of mktemp that comes with Mac OS X 10.8.3

**Comment by psimonyi** [comment]
Looks as if we should be using `-t` then.
