### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#162]
While viewing comments on a piece of code, the tutorial tries to highlight the comment submission box (which isn't displayed) and fails miserably.

**Comment by psimonyi** [comment]
Is this related to #93? I don't understand the description.

**Comment by spratt** [comment]
Alright, steps to reproduce:
1. go to a page with code like http://review.steamedpears.com/index.html?id=f9ff145f-4d64-49c0-9269-ceaba53efdc7
2. click on the code somewhere to bring up the comment submission box
3. click on a comment button (at the time of writing this, there is one comment on line 2)
4. click the tutorial button
5. click the next button

You should see something like this:

![Screen Shot 2013-04-19 at 6 04 28 PM](https://f.cloud.github.com/assets/80992/404226/2ac4a550-a93d-11e2-9fc8-df906c86ed12.png)

Notice that the tutorial is tightly packed into the top left corner of the screen.
