### ISSUE TITLE
What are your actual names?

### ISSUE THREAD

**Issue by Gankra** [SteamedPears/Code-Review#2]
Post your actual name so we can associate them with your github accounts. This will be your mark for T2.

**Comment by psimonyi** [comment]
Commit 6e9a100. (also each of our accounts is associated with the owner's real name)

**Comment by Gankra** [comment]
Ideally we'd like to be able to associate your account with your name (so commenting in this issue with your name would be the easiest [I am not your TA]).

**Comment by spratt** [comment]
This is Simon Pratt.

**Comment by bheesham** [comment]
This is Bheesham Persaud.

**Comment by psimonyi** [comment]
This is Peter Simonyi.

**Comment by psimonyi** [comment]
... but look at https://github.com/CarletonU-COMP2406-W2013?tab=members and you won't have to wait to find out Christian's name!

**Comment by cdelahousse** [comment]
Christian Delahousse
