### ISSUE TITLE
Use new index form fields

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#20]
_Imported issue by **[Gankro](http://github.com/Gankro)** from 2012-07-23T03:03:52Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/72_

---

Title: Title of code
Custom ID: Custom URL to use, must verify it is not taken (and does not contain special characters)
Parent: the ID of code this is forked from
Encrypt Page (See Issue #71)

**Comment by spratt** [comment]
Closing because these are separate issues.
