### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#24]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-15T04:51:10Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/60_

---

Now that the interface is actually usable, we should start thinking about user experience.  When the user first submits code, they are presented with a page that shows their code and whole bunch of empty space.  If no comments have been made, we should have something which lets the user know they can select lines in the code to comment.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T05:05:24Z_ *

---

This seems doable. Something like:
[box with arrow pointing to code]
"Select a portion of the code to comment on it or suggest a change."

If they select it:
[box appears below the comment box]
"Nice! Here you can discuss the selected portion of code. You can edit this copy of the code to provide suggested changes too!"

If they submit it:
[box pointing to comments button]
"Awesome! Click here to see your comment!"

And then maybe something about merging.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-15T05:07:53Z_ *

---

Exactly what I was thinking.  Nothing complicated.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T05:12:48Z_ *

---

The question is just when to show it. We could show it to a new user the first time they submit code. What about an anonymous user? Every time? What about a new/anonymous user who isn't submitting code but has just been linked to this code base. What if there's already some comments on it?

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-15T05:29:49Z_ *

---

I think we should show it any time there are no comments.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T15:47:48Z_ *

---

I dunno, I feel like being "f1rst" is generally a rare phenomenon. Anyone who doesn't get it won't have any way to know.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-17T01:02:00Z_ *

---

I think to a large extent, users will see other comments and try to figure out how to leave their own.  Though if you have a better suggestion, I'd be interested to hear it.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-17T02:36:48Z_ *

---

It just doesn't seem intuitive. Especially since I just disabled clicking on a line to comment (must select). I'm at a loss for a superior alternative.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-18T17:06:26Z_ *

---

We'll talk about it at the meeting tonight.

**Comment by spratt** [comment]
@psimonyi you should chime in on this as our HCI expert.

**Comment by spratt** [comment]
This library does _exactly_ what I wanted to do for the tutorial: http://usablica.github.com/intro.js/

**Comment by spratt** [comment]
Another possibility: http://www.zurb.com/playground/jquery-joyride-feature-tour-plugin
