### ISSUE TITLE
0-index versus 1-index

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#25]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-15T02:01:29Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/53_

---

CodeMirror stores lines in 0-index format, whereas the backend stores lines in 1-index, which leads to lots of off-by-one errors.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T04:39:15Z_ *

---

I would wait on this until way have absolutely settled on continuing to use CodeMirror.

**Comment by cdelahousse** [comment]
_Imported comment by **[cdelahousse](http://github.com/cdelahousse)** from 2012-07-18T23:59:29Z_ *

---

We may be changing syntax highlighter. This issue depends on that change. This issue will remain open until we've resolved that issue.

**Comment by spratt** [comment]
I think we settled on switching to Ace, and the switch is partially implemented.  At the very least, we're importing Ace in the front end, but I think we're still using CodeMirror.

**Comment by spratt** [comment]
Backend now stores lines in 0-index.
