### ISSUE TITLE
CodeMirror expansion is broken

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#26]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-15T01:54:46Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/51_

---

CodeMirror is set to expand so that it doesn't have a scroll bar, but it usually fails and the observed behaviour is that it has a scroll bar, but when you scroll, the scroll bar disappears.

We can probably get rid of this by forcing CodeMirror to refresh well after the page is fully loaded, like with a setTimeout call.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T04:38:42Z_ *

---

Aggressively applying and re-applying refresh() even after waiting intervals seems to be ineffective against this issue. Counting this as a point for ditching Code Mirror.

**Comment by spratt** [comment]
This doesn't seem to be an issue any more.
