### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#33]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-05T14:16:40Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/24_

---

We may want to create a minification script that "compiles" the source into minified versions for deployment.

**Comment by spratt** [comment]
If we're using requirejs http://www.requirejs.org/ it comes with a tool to optimize load time called r http://www.requirejs.org/docs/optimization.html which bundles together related scripts (since it knows about the relationship between scripts) using uglifyjs or closure, and inlines CSS.

**Comment by cdelahousse** [comment]
Do we know how requirejs' optimzation script works with the rest of the front end js? Uglify runs in the command line, so why don't we just have a custom build script that minifies everything for us and outputs the site in a format ready for production? Make files rule.

**Comment by spratt** [comment]
requireJS should be taking advantage of the fact that it knows how the modules relate to one another.  r.js runs from the command line, so it's not mutually exclusive with a "custom build script."

**Comment by spratt** [comment]
@cdelahousse This should be a big part of our scalability audit.  Let's send less characters over the wire and open less TCP connections.

**Comment by cdelahousse** [comment]
I'm working on writing some production build scripts. @spratt, were you planning on using the requireJS build procedures?

**Comment by spratt** [comment]
@bheesham is ostensibly working on production build scripts.

Yes, we should use the requireJS build script r.js.  It knows what files we actually depend on, so it can build a dependency graph and put everything together sanely.

**Comment by cdelahousse** [comment]
Shit. So my work this morning has been for naught. I'll show you what I was
thinking

**Comment by spratt** [comment]
I suspect it won't be completely for naught.  We should handle minification as a separate issue from deployment because it's kind of a big deal and there's lots of ways to do it.

**Comment by spratt** [comment]
Sorry, I was still waking up.  @bheesham is working on production _deployment_ scripts.

**Comment by spratt** [comment]
It looks like the r.js optimizer does exactly what we want.  It builds the dependency tree of explicit require calls (not including the dynamic ones we load for syntax highlighting), then packages all those files together in one file and (by default) calls uglifyJS on it.

**Comment by spratt** [comment]
The syntax highlighting files will have to available separately and (ideally) individually minified.

**Comment by spratt** [comment]
See #31 for my discussion on testing.

**Comment by cdelahousse** [comment]
Closed #113
