### ISSUE TITLE
Stop using do/languages

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#34]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-05T14:01:19Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/23_

---

Since we already have languages.json, we don't really need to have languages stored in the database.  I'm thinking we should change the unique ids of the languages from numbers to their short-names such as "js" which are already stored in languages.json.  This will reduce the number of ajax calls we need, and reduce the number of calls to the backend code, which should increase scalability.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-13T21:00:12Z_ *

---

Since this is mostly a backend thing, I'm assigning this to Christian.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T05:28:32Z_ *

---

Could we just have do/languages link to langauges.json? I kind of like the uniformity/implementation-neutrality of do/languages as a URL.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-15T05:36:00Z_ *

---

That is probably doable, but I like putting as little strain on the backend as possible.  The less the backend gets hit and the more we can use a cached static front end, the more requests we're going to be able to satisfy in some unit time.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T15:49:18Z_ *

---

How much cost does a hardlink from do/languages to languages.json incur?

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-17T01:03:03Z_ *

---

The back end is single threaded, so every request for a hard linked file would delay the processing of actual requests.

**Comment by spratt** [comment]
Alright, so right now information on languages is split and duplicated on the front end and backend.  See src/server/languageList.js and src/client/languages.json.  We should really put all the languageList.js information into the languages.json file and remove all the languages information from the back end.  We've already eliminated the languages table in the db.

**Comment by spratt** [comment]
Closed by 0715734b90bb9903718f194a4f8930f334f634ef
