### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#35]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-05T13:57:30Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/22_

---

The code is starting to get a little hairy.  We should probably do some serious review and clean it up.  There's lots of code duplication, both within view.js and duplicated code across index.js and view.js.  We should refactor to use the javascript module pattern, and separate the code into shared code and index/view specific code.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-06T22:09:52Z_ *

---

Can you reference specific areas that are duplicated? I don't see anything that is really bad at this point. Except for maybe mapping line number into {line:,ch:} format.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-13T21:01:59Z_ *

---

The html for index and view are almost identical, and much of the utility functions between index and view are shared.  Index and view can probably be merged into one file that displays the code submission form if no id is specified and if an id is specified, show the code with that id.

**Comment by spratt** [comment]
I think we should pull out related functionality into modules and switch to a requireJS style of combining them.

**Comment by spratt** [comment]
Closed by 0715734b90bb9903718f194a4f8930f334f634ef
