### ISSUE TITLE
Github Flavored Markdown broken

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#36]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-07-05T13:54:04Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/21_

---

This is caused by the fact that GFM may contain any other language, so it has to load ALL the languages.  We should implement some kind of progress bar, or any kind of indication that the page is still loading.

Update February 19th, 2013: after the front-end rewrite (and CodeMirror update), GFM is completely broken.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-06T22:10:41Z_ *

---

Maybe don't support github markdown? That seems excessive.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-07-14T21:56:58Z_ *

---

That's probably the right thing to do.  We could just treat GFM as regular Markdown from now on.  Or include a couple of the most popular languages.  I suspect it doesn't fail horribly if it doesn't have a language loaded when it encounters that language.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T05:21:36Z_ *

---

You are the maintainer of this feature. Assigned to you.

**Comment by spratt** [comment]
Since we may be switching to Ace, I'm going to unassign myself and put this on the backburner until the dust has settled.

**Comment by spratt** [comment]
At this point, github flavored markdown is completely broken.  It's not clear why.

**Comment by spratt** [comment]
Selecting Github Flavored Markdown from the drop down menu gives the folllowing javascript error: 

```
TypeError: CodeMirror.overlayMode is not a function
```

**Comment by spratt** [comment]
I have a feeling this broke because we updated our version of CodeMirror and now we're using outdated options.
