### ISSUE TITLE
Don't grab all comments at once

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#41]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-06-26T14:36:00Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/4_

---

We should probably just grab the comments in limited amounts.  50 at a time, maybe?  This should make the page more responsive when there are lots of comments.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-06-27T18:19:58Z_ *

---

As it's designed now we could store with the code a map of line numbers to comment numbers. Then only when someone clicks on the (#) do the comments get AJAX loaded in. I dunno how this would work with the back end, loading all the comments from one specific line, that is. 

If there's too many comments on one line we can just load in the first 50 or something and have a "more..." button at the bottom that loads the next 50. Again the main challenge here is a back-end matter.

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-06-29T05:46:20Z_ *

---

On the backend, it would be easy just to get the comments on a specific line number.  Would it hurt responsiveness?  We may want to think about the case where there are hundreds of comments on one line.  Then again, we may want to leave that for our future selves to deal with.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-07-15T15:59:21Z_ *

---

Details on expected resolution strategy here: https://github.com/SteamedPears/CodeReviewClientMaster/issues/46#issuecomment-6987610

**Comment by spratt** [comment]
Detailed resolution strategy in this repo: https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears/issues/27

**Comment by spratt** [comment]
The front end now loads comment counts from the comment model, then only loads comments on a particular line when the button is pressed.  All that's left is implementing this in the backend and setting the front end up to take advantage of it.
