### ISSUE TITLE
Scrape, Github/Gist, various vendor bookmarklet

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#43]
_Imported issue by **[spratt](http://github.com/spratt)** from 2012-06-26T14:33:20Z_
_Originally opened as https://github.com/SteamedPears/CodeReviewClientMaster/issues/2_

---

We should be able to make a bookmarklet that scrapes the plain text of code in a github repo or a gist and pulls it into our editor.

**Comment by cdelahousse** [comment]
_Imported comment by **[Gankro](http://github.com/Gankro)** from 2012-06-27T18:16:40Z_ *

---

Specific files or entire code bases? Should there be any meta-data that associates related files (e.g. as part of the same project or package)?

**Comment by cdelahousse** [comment]
_Imported comment by **[spratt](http://github.com/spratt)** from 2012-06-29T05:44:18Z_ *

---

For now: specific file, ignore meta data except what language the file is in.

**Comment by spratt** [comment]
I don't think we need to even scrape anything.  I think github gives blob (plain text) access to files.  Not sure about gists, but I know every file in a github repo has a blob url.

**Comment by bheesham** [comment]
Simon and I were talking about this. Github, and Bitbucket surely have some API. Otherwise, we can (hopefully) use the method Simon suggested above. We were talking about this on our way to CUSEC.

**Comment by psimonyi** [comment]
http://developer.github.com/v3/gists/#get-a-single-gist

**Comment by cdelahousse** [comment]
Sexy, I love this idea.

**Comment by psimonyi** [comment]
I guess we would import the gist and maybe have a link back to the source. I'm working under the assumption that CodeReview snippets are immutable.

**Comment by bheesham** [comment]
I don't think we should really focus on Gists, and Github repos right now.
The main reason being, I would want to integrate with more than just Github, and do more than just public repos.

We should instead create the app, where we can add "vendors"? Vendors being different git repository hosting providers, such as Bitbucket.

I think I mentioned this in one of the issues, and definitely on the way to CUSEC with @spratt .

**Comment by cdelahousse** [comment]
I could see us having one bookmarklet as a gateway. it would detect the vendor via it's URL and then async load the vendor specific JS. 

If we start adding vendors, though, it'll be harder to develop. I really like the idea of a bookmarklet, though. Why don't we start with something simple, like scraping content from a page a la readability/instapaper/pocket/readitlater. That shouldn't be too hard to implement and we'd quickly have a prototype for a bookmarklet that'll work almost anywhere.

**Comment by bheesham** [comment]
Yeah, bookmarklet's are cool and all, but not for someone who doesn't have a bookmark bar. http://prntscr.com/rv6xg

And as for the vendor thing, I'd rather someone not copy and paste each file they want reviewed. It'd be nice to have a file-file associations. Something that could be used to write better unit tests, or troubleshoot something between two PHP files where one includes the other. I think that's a real thing. Chances are, if you want something code reviewed, you want to make it better, or solve some problem that you yourself can't solve. And most of the time, these problems have more than one file. Not always though.

**Comment by cdelahousse** [comment]
I'm marking this as closed because we have a working prototype.
