### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#45]
Need to figure out how to easily deploy new versions of the app to the production server.  Ideally this should be as automated as possible.

**Comment by bheesham** [comment]
I think that the scripts you prepared would do fine. Something along those lines.

**Comment by spratt** [comment]
I like using nginx to serve the static files, and webfaction requires the static files to be in a different directory.  Also, production will be using mysql or postgres.

**Comment by cdelahousse** [comment]
What'll be the process to deploy? Can anybody to it? When is does the build get to a deployable state?

**Comment by spratt** [comment]
@bheesham It would be really awesome if you could finish this when you have time.  

Check out this article on deploying node.js to webfaction to see the issues we need to solve: http://shkfon.tumblr.com/post/27178918675/real-world-nodejs-part-1

**Comment by psimonyi** [comment]
Is this resolved by #126? @spratt

**Comment by spratt** [comment]
Yup.
