### ISSUE TITLE
Search for new Syntax Highlighter

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#47]
Original: https://github.com/SteamedPears/CodeReviewClientMaster/issues/68

Code Mirror causes a lot of issues. In this project, most of the time we work with the library, we're working against instead of with it.

We no longer need syntax highlighting WHILE editing, although that feature would be a nice to have. That feature was the reason we originally chose Code Mirror.

**Comment by cdelahousse** [comment]
From @gankro
Github uses Ace: http://ace.ajax.org/

Seems really robust. Also doesn't even flinch at jquery.js

**Comment by cdelahousse** [comment]
It looks like we've decided to switch to Ace. I'm closing this issue.

**Comment by cdelahousse** [comment]
Reading through the other issues, it seems as if this hasn't been decided. I'm reopening the issue.

**Comment by bheesham** [comment]
No no, we're switching to Ace. Code Mirror is just so slow, and a little hard to work with, but I think that's just because we weren't working with the JS, but rather the HTML output.

**Comment by spratt** [comment]
Alright.  We're switching to Ace unless we discover something wrong with Ace.  I'm closing this issue and opening a new one to switch to Ace.
