### ISSUE TITLE
Are we merging the front end and rear end into one repo

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#5]
Our current code base was shared between github and bitbucket for the front end and back end, respectively. How will we be managing this divide?

**Comment by spratt** [comment]
I was strongly considering doing this for a while since they are necessarily pretty tightly coupled.  They shouldn't be in the same directory on the server, since the front-end is served statically and the back-end is executed and the result is served.  Should be fine.

**Comment by Gankra** [comment]
We have 300 private repos, but only like 50-60 groups. So it wouldn't be impossible for us to allocate multiple repositories, as long as one is the "main" one (e.g. client and server are git modules of this one). I would need to confirm this with @asomayaji, though.

**Comment by cdelahousse** [comment]
I'd really like to see everything in one repo. It's just easier to manage the project. If I need to clone the project on some computer, minimal configuration will be needed to get it running locally. No copying repos into repos or what not.

Also, when we run the node instance in dev mode, we're emulating what simon's done on the server. Running in dev mode creates a server that acts as back end storage and another that is the static file server for the front end. The file server points to the folder where lies the front end code.

Originally, we has two repos to hide the back end source from the public. We now have access to private repos, so why bother splitting the project into private and public repos?

I don't see a need for two repos. It adds unecessary complexity.

**Comment by spratt** [comment]
Yes.  Let's merge them.

**Comment by cdelahousse** [comment]
I'd like to hear from at least one more team member before we do anything.

**Comment by spratt** [comment]
Agreed.

**Comment by bheesham** [comment]
I'm all for merging and stuff. But I suggest that we merge it into a different branch, because we'll be rewriting it, using the "old" branch with both the client and server, only as a reference.

**Comment by psimonyi** [comment]
I'm all for merging. (There's also the option of repo-in-repo, but that seems like possibly overkill.)

**Comment by spratt** [comment]
Done.  See 54116899bca1c91e66bbe60d2915d713ae33e640
