### ISSUE TITLE
Architecture diagrams

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#50]
We said we'd have architecture diagrams ready for this tutorial.  I'm thinking something very high level, simply describing the basic interaction between client and server, and what libraries each will use.

I'll do up a quick thing of what I'm thinking, submit it here and we can discuss.

**Comment by spratt** [comment]
![Code_Review_arch](https://f.cloud.github.com/assets/80992/133339/06da765c-70a7-11e2-8da9-65abe76526c3.png)

**Comment by spratt** [comment]
Added bookmarklet client
![Code_Review_arch2](https://f.cloud.github.com/assets/80992/133378/f0cf2c98-70a8-11e2-8319-0398f33882f2.png)

**Comment by spratt** [comment]
I've also created this description of the server API: https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears/wiki/Server-API

Let me know where it can be improved.

**Comment by spratt** [comment]
I'm guessing this is good enough?  

@psimonyi mentioned that the bookmarklet might contact the web client, which would actually make a lot of sense.  If it would dump the scraped text into the input text box for a final review, that might be awesome.

@cdelahousse do you have any libraries you're thinking of using for the bookmarklet tool?  If so, let's add them.

**Comment by cdelahousse** [comment]
Maybe require or some other asyc loading library

**Comment by cdelahousse** [comment]
@psimonyi good idea. I'll have it as an option. Well need to implement something on the front or back end because I don't know if there's a way to populate a text field via a request on the front end without some code

**Comment by spratt** [comment]
If you pass it in as a parameter like index.html?text="blah blah blah" then we can use javascript to grab the text and populate the field.

**Comment by cdelahousse** [comment]
That's exactly what I was thinking. Isn't there via limit on the size of
get request args though,?

**Comment by cdelahousse** [comment]
Whoop. We shouldn't use this issue to talk about the bookmarklet

**Comment by spratt** [comment]
It is part of the architecture.  Should I change the diagram?  If so, how?

**Comment by spratt** [comment]
This will be our architecture for Sprint 1.

![Code_Review_arch3](https://f.cloud.github.com/assets/80992/137656/3e70b0ce-7177-11e2-904d-c4072590a9ab.png)
