### ISSUE TITLE
Choose an issue to work on for Sprint 1

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#51]
Make sure to assign it to the Sprint 1 milestone

@bheesham @cdelahousse @psimonyi @spratt

**Comment by bheesham** [comment]
Hmmmm. I'd like to tackle the sharing URL.

**Comment by bheesham** [comment]
I feel as though I'd learn more from doing work on the back-end.

**Comment by cdelahousse** [comment]
Bookmarklet

**Comment by spratt** [comment]
@bheesham The back end needs some cleaning up for sure.  If what you want to do doesn't have an issue, make one and assign it to yourself.  If you have assigned yourself an issue, make sure to add it to the Sprint 1 milestone.

**Comment by spratt** [comment]
@bheesham will be working on shortened/share URLs #49 , @cdelahousse will be working on the bookmarklet #43 , @psimonyi will be working on Persona integration #39 , and I will be working on cleaning up the code base #35
