### ISSUE TITLE
Let's have a nice design

### ISSUE THREAD

**Issue by psimonyi** [SteamedPears/Code-Review#53]

**Comment by spratt** [comment]
Ideally clean and minimalistic.  Interface clutter is a barrier to entry.

**Comment by psimonyi** [comment]
Here's the scanned version.
![CodeReviewUI_mockup](https://f.cloud.github.com/assets/1505456/262211/7fa8f8bc-8d1f-11e2-9a21-627b960d60d3.jpg)

**Comment by cdelahousse** [comment]
Ha! I'm in the example!

Can you explain the second figure down from the top? Is that the client in tutorial mode?

Why are the comments to the right AND the left?

Can you give a bit of context to the figures?
