### ISSUE TITLE
Codify dev conventions and document certain parts of the process

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#6]
## Dev conventions

I want this project to have legs and continue well beyond the end of the course. I think an addition that would keep us on track would be to codify some of the agreed upon conventions using the provided github wiki.

For example, every pull request must be merged by someone other than the pull-ee.

Please list any suggestions you have.

We should also consider closing or actioning an issue after a majority of the team agrees.
## Documenting dev process and decisions

I think we should document larger design decisions because this stuff is hard to capture just using git commits.

**Comment by bheesham** [comment]
So for discussing the issues, features, etc, I think that using Issues on Github would be a good idea. Then once we've figured out what we actually want, add that to some sort of specs page on the wiki.

I don't think we should ever do it through git commits, unless it's finding something we need to discuss. So if someone wants to implement something, and run into a problem, commit changes, then create an issue. We'd be able to discuss, then document it, and finally implement it.

**Comment by spratt** [comment]
I have created https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears/wiki/Process

Let's use the wiki to document process.

The question of documenting design decisions is harder.  I think we should use issues to document design problems, and discuss the solution in some detail in the resolution of the issue.

@psimonyi What do you think?

**Comment by psimonyi** [comment]
Sure, I like wikis. Significant design decisions probably deserve to be in the repository, either in their own files or in block comments.

**Comment by spratt** [comment]
We've decided to document the design decisions and public APIs as specified in https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears/wiki/Server-API
