### ISSUE TITLE
Modeline before html tag puts IE in quirks mode

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#62]
See discussion at https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears/commit/eb561aeebd3ab0dd7824704ba58e12d77ed66007#commitcomment-2669648

**Comment by bheesham** [comment]
Also, not setting the doctype will put some browsers into quirks mode for those who didn't read the discussion.

So, modeline after doctype.

**Comment by cdelahousse** [comment]
Vim modelines DO NOT need to be near the top. They can be near the bottom too.

http://vim.wikia.com/wiki/Modeline_magic

Just an FYI.

**Comment by psimonyi** [comment]
Oh, cool. I thought they had to be at the top. Maybe the bottom is better...

**Comment by bheesham** [comment]
[Yes, the bottom is better.](http://www.hiyoooo.com/)

**Comment by spratt** [comment]
Cool.  I will leave it to you guys to handle this.  

I haven't yet found an equivalent to vim modelines in emacs.  There's a thing called the modeline, but it is a part of the UI that displays (among other things) what mode the editor is in.

**Comment by psimonyi** [comment]
This is mostly needed because of using tabs... is it bad form to bring
that up? 'Cause I'd like to revisit the decision...
http://www.jwz.org/doc/tabs-vs-spaces.html

**Comment by spratt** [comment]
We resolved this, determined that emacs and vim can have modeline-like things and tabs suck.

**Comment by cdelahousse** [comment]
@psimonyi I've updated the modeline. tabwidth=8 was not a valid setting.

**Comment by cdelahousse** [comment]
Can we close this? Why did @psimonyi reopen the issue? Are we waiting for @spratt to come up with his own File Variables?

**Comment by psimonyi** [comment]
The bug is "Modeline before html tag puts IE in quirks mode". The resolution is a code change, e.g. #71.
