### ISSUE TITLE
Production server deploy scripts

### ISSUE THREAD

**Issue by bheesham** [SteamedPears/Code-Review#64]
I'll be working on getting this to work on a production server, since I can't code on my netbook, or get it working through Windows.

Great. Great great great.

**Comment by bheesham** [comment]
Seems as though all you need to do is change the location of the executables, and add one for the location of NPM.
That, and configure NPM.

Instructions to come.

**Comment by spratt** [comment]
Marking this as a duplicate of #45 and closing this issue.
