### ISSUE TITLE
Reorganize the back-end

### ISSUE THREAD

**Issue by bheesham** [SteamedPears/Code-Review#67]
We should reorganize the back-end. For a simple web-app, it's "fine". But for something that we'd want to scale, not so much.

We should have a meeting at some point.

Since we're going to be reorganizing the back-end, we might find a better way to write our public API, so @cdelahousse and @psimonyi will have to be kept in the loop.

@spratt

**Comment by bheesham** [comment]
@spratt , check out my fork in the `restructure` branch.

The structure we have in place, is what I'd like to see happens.
I don't mind if it changes a lot, I just care about it staying organized.

**Comment by bheesham** [comment]
@spratt @psimonyi @cdelahousse Checkout the `restructure` branch on my fork, give feedback.

**Comment by spratt** [comment]
My biggest question without access to my laptop is: does it still run?

Other questions:
- Why _init.js?  Is it a common pattern?

Observations:
- Looks much cleaner.
- I like the pattern of code inside of a require statement.  This is a really nice way of exposing components only to the libraries they need.
- Much of the code you've added is indented with tabs.  D:

**Comment by bheesham** [comment]
It runs, just not completely re-written, so a lot of things are missing.

_init.js so as to differentiate what initializes classes from the actual classes.
- Thanks
- Yep, but I think Node does that for you anyways if it's in a module on it's own
- Sorry, blame my `.vimrc`

**Comment by cdelahousse** [comment]
I've cloned your fork at commit 800b5bca05d80155cf6ebfffdaf9528aa990ff20. It breaks the bin/start_script.sh script. 

db_info.js.sqlite, build_db.js, test_data.js are missing.

I can't comment on your repo. I'm starting to agree with Peter that Github sucks.

**Comment by psimonyi** [comment]
Simon says the start script starts node on index.js, but now it should use _init.js, so that's probably why it doesn't work.

**Comment by cdelahousse** [comment]
My stupidity knows no bounds. I forgot this was a "work in progress". I was going through your code thinking "where did everything go?" Sigh.

Forget my last comment.

Good job. It looks really nice. Really clean. I like how you've broken down the server into a couple of "classes" with "subclasses". Super easy to extend.

**Comment by cdelahousse** [comment]
Here's a kitty:
![Kitty](http://img0.etsystatic.com/000/0/5280812/il_570xN.340900784.jpg)

**Comment by cdelahousse** [comment]
I'm not a fan of your DB defaults. We'll probably be cloning repos to dev machines so SQLITE would be a better choice. The only installation that'll use MySQL is the production machine.

**Comment by bheesham** [comment]
Yep, you can change that all in the db.ini file. So if you set them to blank, it'll work just fine (or should) with sqlite.

**Comment by bheesham** [comment]
Also, do not try to run it using the scripts. You'll have to do `node app.js` to run it.
I have not yet modified the scripts in `bin/` to work with the new setup.

**Comment by cdelahousse** [comment]
I'm a bigger fan of using `node app.js` anyways.

**Comment by spratt** [comment]
You prefer running `node app.js` to running the shell scripts that set up your modules and database and then calls `node app.js`?

**Comment by cdelahousse** [comment]
Yes. I love scripts to set up a project, but I don't like them starting the app. I d rather the output go to the console and use something like node watch instead of node.

**Comment by spratt** [comment]
Anything you can do from your command line, we can do from the script and we are guaranteed to start in the same state which is useful for testing.  

I also like the script because it encapsulates how the environment should be started, so you don't have to remember that to start the server you run `node app.js` in the /src/server folder.

**Comment by bheesham** [comment]
I agree with Simon. I don't like the idea of having to navigate to src/server to start the server. We have a bin/ folder, we should use it.

**Comment by psimonyi** [comment]
Ideally, the script would use a NODE environment variable, if it's
defined, instead of "node" -- so you can do
$ NODE="node watch" bin/start_dev.sh

**Comment by spratt** [comment]
I'm pushing this tentatively to Sprint 4.

**Comment by spratt** [comment]
I think we can consider this done based on the recent pull requests.  @bheesham what say you?

**Comment by bheesham** [comment]
I agree. Your rewrite took out most of the grossness I didn't like.
