### ISSUE TITLE
We need to pick our tasks for Sprint 2

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#69]
Reply to this issue with your task for next week, and reference the issue number.  Try to be realistic about how much you can finish in a week.  Add your issue to the Sprint 2 milestone.  Assign the issue to yourself.

@bheesham @cdelahousse @psimonyi

**Comment by spratt** [comment]
I'll work on #57

**Comment by bheesham** [comment]
I'll work on #67

**Comment by psimonyi** [comment]
I'll work on #53.

**Comment by cdelahousse** [comment]
#70, I work on.
