### ISSUE TITLE
Style guide to wiki or keep as text file.

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#7]
Over the summer, we sketched out a style guide. I think we should use the facilities provided by github and move it to the wiki instead of having it live in a text file.

Original issue:
https://github.com/SteamedPears/CodeReviewClientMaster/issues/44

Bhee made a first draft:
https://github.com/SteamedPears/CodeReviewClientMaster/blob/master/CODING

**Comment by psimonyi** [comment]
My first reaction was approval — I like wikis. However, on second thought, I'm not sure what benefit the wiki has over a plain text file in git. (Also, _tabs_?)

**Comment by cdelahousse** [comment]
If our documentation grows, text files may grow unwieldy. Wikis allow
formatting, categorizing, linkng, etc.

I think the biggest drawback is that having a wiki will make us depend more
on github. We won't be as portable. I coukd say the same thing about using
the milestones and issues features.

Many bigger projects make use of github wikis. The HTML5 boilerplate isv a
good example.

**Comment by psimonyi** [comment]
Github wikis seem to be markdown files in git repositories, so it's relatively portable. I'm convinced.

**Comment by cdelahousse** [comment]
We've two members in favour. I'd like to hear from one more.

**Comment by spratt** [comment]
Wiki is good.

Stop trying to get a majority for every decision.  Make the plan known, anyone who disagrees with the plan can object.  Otherwise, just do it.

**Comment by psimonyi** [comment]
Done.
