### ISSUE TITLE
Let's have the bookmarklet have a nice design

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#70]
Like #53, but for the bookmarket.

**Comment by cdelahousse** [comment]
I finished my mock design. See a0fbbffc94f19d275c449c49edfedd40c880c47e

**Comment by spratt** [comment]
"delete window.codeReview"?

**Comment by cdelahousse** [comment]
Yes. It deletes prior instances of the bookmarklet.

**Comment by spratt** [comment]
How is that related to a mock design?

**Comment by cdelahousse** [comment]
It's the last commit on my bookmarklet branch. I shoulda linked to the branch, no the commit.
