### ISSUE TITLE
Can we use Connect.js?

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#72]
I'd really like us to convert to connect.

1) it gives us a lot of tools we'll need in the future.
2) Better session management, form parsers, better request handling, etc (via object extensions)
3) A baked in static file server.
4) it's very lightweight.
5) a plugin architecture so that you can hook in anything into request.

It's well built and widely used.

Please peruse the API:
http://www.senchalabs.org/connect/

Why do I want it?
I'm trying to implement CORS for my bookmarklet. I'm seeing that there needs to be a few preflight HTTP requests to allow cross origin resource sharing. If we want to implement this for more than one request handler, I need to write a function that catches the request and sends back a response with a special OPTION header. I can't think of an elegant way to do this.

The solution with connect is simple and elegant. I just write a small piece of middleware and BOOM, problem solved.

I know @spratt hates Express. Connect doesn't force us to use a framework like express does. It's just a nice set of tools.

I don't think converting to Connect will be difficult. We may only need to change like 10 lines.

**Comment by cdelahousse** [comment]
Here's a list of great plugins that are designed to work with connect:
https://github.com/senchalabs/connect/wiki

**Comment by spratt** [comment]
Didn't you already implement responding to the preflight request?  In #58 ?  And #63 ?

**Comment by spratt** [comment]
I don't hate Express in particular.  I'd like to hear what @bheesham and @psimonyi think about using Connect or Express.

**Comment by cdelahousse** [comment]
#58 and #63 solved half of the problem. I just fixed the rest about 15 minutes ago, but it is a gross hack. One you'll see in tonight's pull request.

**Comment by spratt** [comment]
Can you be more specific about exactly what the server needs to do?

**Comment by cdelahousse** [comment]
The server needs to respond to a preflight HTTP request using the OPTIONS method. The server's response should include a few headers allowing more CORS request. After that, both the client (bookmarklet) and the server (CR) can send CORS requests without needing to do more.

My issue is that if we want to catch requests with the OPTIONS method, we need to explicitly do it in every request handler. Using middleware, we could implement it only once and have it work for all the API.

**Comment by spratt** [comment]
What headers exactly?  Can you point me to the connect.js middleware that would make this easy?  Would it replace our current router?

I don't think we should accept cross domain requests to anything except /do/newcode, which as far as I understand is what you implemented before.

**Comment by cdelahousse** [comment]
Implementing CORS would be something along the lines of:

```
function cors(req, res, next) {
  if (req.method.toUpperCase() === "OPTIONS") {
      res.header('Access-Control-Allow-Origin', "*");
      res.header('Access-Control-Allow-Methods', 'GET,POST');
      res.header('Access-Control-Allow-Headers', 'Content-Type');
  }
  next();
}

app.configure(function() {
   ...
   app.use(cors);
   ...
});
```

It would not replace our router.

Besides implementing CORS, I'd like to hear what you thing about using Connect JS in general. I see it being an asset down the line, like when we implement authentication or need to work with sessions.

On a personal note, I'd like to learn how to work with a popular Nodejs library. I see connect everywhere and I'd like to see what the fuss is about.

**Comment by bheesham** [comment]
`shipping with over 18 bundled middleware`
First thoughts: not really discussion encouraging.

For logging, I was looking at [Riemann](http://riemann.io/dashboard.html). It looks great, and simple to setup. It does require a bit more work to do so, but we'd be able to make a pretty damn nice back-end. And by bacn-end, I mean something along the lines of an administrator's interface. It's not ideal to handle things through the command line. I like numbers. I like graphs. I like to see what people are up to, without having to look at a console.

As for the other middleware, we can just use what we need. I don't see a reason to install connect, when all we'd be using are the 3rd party middleware. 

`favicon`, oh fuck right off. We don't need that, that's why we have a static server. 

`query`, `ResponseTime`, `timeout`, all seem useful. Sessions and stuff, yeah those too.

**Comment by bheesham** [comment]
Use what you need, if I cringe at any code I'll write you a strongly worded letter.

**Comment by spratt** [comment]
@cdelahousse that code looks like you could run it with the regular router as the next callback.  Also, it looks like it handles OPTIONS for every request URI, which I think is a bad idea.  I think we should only allow CORS for /do/newcode, in which case we only need to add these headers to the newcode request handler.

**Comment by psimonyi** [comment]
I don't see why we shouldn't use Connect if there's something someone wants to use it for. It seems like a bunch of tools, some of which would be handy and some not. It doesn't seem that it will have an impact on unrelated parts of the code.

**Comment by bheesham** [comment]
Yep, @cdelahousse , @spratt  and I talked about this today. We decided that it was cool to use it.

**Comment by psimonyi** [comment]
The answer to the question is "yes", so I guess this is closed. (Converting existing code to take advantage of Connect.js would be another bug.)
