### ISSUE TITLE
Use linting

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#76]
We're not using JSHint as much as we should.

We should also choose some good defaults. For example, there's an option that tells JSHint that some code will run in the browser. This will suppress the error telling us that 'console' has not been defined.

**Comment by psimonyi** [comment]
Try [psimonyi:lint](https://github.com/psimonyi/Steamed-Pears/tree/lint)

**Comment by cdelahousse** [comment]
Those settings seem sane.

There doesn't seem to be much difference between the jshintrc files. Couldn't we just have one in the root directory? The problem I see with that would be different dev environment setting. One should be the browser, the other is Node.

**Comment by psimonyi** [comment]
Exactly. We could:
1. Fork JSHint so it merges configuration files
2. Generate the .jshintrc files (e.g. with make) from a common source
3. Add a `/* globals: ... */` declaration at the top of each file
4. Just have some duplication until someone else does 1.

I'm in favour of 4.

**Comment by cdelahousse** [comment]
Meh. No biggy.

**Comment by psimonyi** [comment]
I agree that the situation is suboptimal.

**Comment by spratt** [comment]
We have some nice JSHint files now.  Peter said that the issue is only sort of closed.  What still remains?  Also, we should do a short write-up on how to add this as a pre-commit hook to git.

**Comment by psimonyi** [comment]
What still remains? Actually doing it. We shouldn't require that commits pass JSHint with no complaints, though: it isn't capable of checking some style requirements. For example, it requires braces around control structure bodies, but I'm perfectly happy with one-line statements like `if (error) return;` --- the argument for braces only applies when the head and body are on different lines.

**Comment by psimonyi** [comment]
However, that's a long-term thing. Let's call this closed.
