### ISSUE TITLE
Transferring previous issues (from old front end repo)

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#8]
There seems to be a tonne of issues in the old repo (https://github.com/SteamedPears/CodeReviewClientMaster/issues?state=open). 

How should we go about transferring them to this one?

**Comment by cdelahousse** [comment]
Found something that may help us. A python script that does some work for you.

https://github.com/mkorenkov/tools/tree/master/gh-issues-import

**Comment by cdelahousse** [comment]
Before I go about importing all the old issues programatically, could you guys take a look at the imported issues in my test repo and see if it's OK. Ignore the closed issues. Some issues need to be imported manually.

https://github.com/cdelahousse/testdeleteme/issues

@spratt @bheesham @psimonyi

**Comment by bheesham** [comment]
Heh, that looks good. But I feel as though most of those conversations are one-sided.

**Comment by spratt** [comment]
You have spammed the hell out of the original issues: https://github.com/SteamedPears/CodeReviewClientMaster/issues/16

**Comment by spratt** [comment]
Otherwise, looks perfect.  :)

**Comment by cdelahousse** [comment]
Woops...

**Comment by spratt** [comment]
Maybe they go away when you delete the testdeleteme repo?  We'll see.

**Comment by spratt** [comment]
I have been informed that there are 5 outstanding issues to be imported.  I'm reopening this.

**Comment by cdelahousse** [comment]
My bad. I jumped the gun. I was super excited to close the issue.

I'll transfer the last few manually.

**Comment by psimonyi** [comment]
@cdelahousse: Now you get to close it twice!

**Comment by cdelahousse** [comment]
Done. All issues but one have been transferred. 

Here's the last one. I'm not transferring it.
https://github.com/SteamedPears/CodeReviewClientMaster/issues/62
