### ISSUE TITLE
Give /do/newcode/ the option of not returning a complete Code object 

### ISSUE THREAD

**Issue by cdelahousse** [SteamedPears/Code-Review#84]
We don't need the content sent back to us over the wire when add some to the DB. I want to create an option for the API not to send it.

An example of why this would be good is the bookmarklet. We only need confirmation and the uuid returned to the client.

**Comment by spratt** [comment]
Actually, I think this is true for the web page too.  The web page already has all the code loaded.

**Comment by cdelahousse** [comment]
Should the default be content returned or no content returned?

**Comment by psimonyi** [comment]
Given that both of the current users don't need it, not sending it seems
like a good default.

**Comment by spratt** [comment]
We may need to modify the client code a little, but the client has all the information it needs.

**Comment by spratt** [comment]
I'm pushing this tentatively to Sprint 4.

**Comment by spratt** [comment]
This is solved in the above pull request.  Turns out the front-end didn't need modification at all, it was ignoring everything except for the id it was getting back.
