### ISSUE TITLE
Prepare for final submission

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#86]
@asomayaji gave us specific instructions for the organization of the final project submission.  We should organize the repo as per the specifications and create the necessary documentation.

**Comment by spratt** [comment]
See http://homeostasis.scs.carleton.ca/wiki/index.php/WebFund_2013W_Final_Project for specifications.

**Comment by spratt** [comment]
Note that the following need to be notable in order to get full marks:
- README.md
- docs/Motivation.md
- docs/Extensions.md
- code style and quality
- overall functionality

**Comment by cdelahousse** [comment]
Extension Suggestions:
Serving the app over SSL.
Private Accounts
Forking

**Comment by spratt** [comment]
Suggestions for extensions?  You should make issues.

**Comment by psimonyi** [comment]
Suggestion: we should make docs/ a submodule, since this stuff doesn't really make sense in the long term. For example, nobody's going to update the architecture diagram, and outdated docs are probably worse than no docs. Also, it might be better not to have student numbers in permanent history.

**Comment by spratt** [comment]
Oh hey.  We're supposed to be done the draft documentation for the end of this week by our original plan.  Let's do that.

**Comment by spratt** [comment]
See https://github.com/CarletonU-COMP2406-W2013/Steamed-Pears-docs

**Comment by spratt** [comment]
This is done.  Just waiting on putting it into the repo.
