### ISSUE TITLE
Use emacs directory variables maybe

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#87]
See: https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

Having per-file local variables that are the same for all files is dumb.

**Comment by psimonyi** [comment]
Sounds good. I think you need a plugin to do this kind of thing in vim.
Beware that you don't accidentally use spaces in Makefiles, for example.

**Comment by spratt** [comment]
Done.
