### ISSUE TITLE
how do we want to run code when jquery document ready

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#88]
I prefer the simpler 

```
$(function() {...});
```

but @psimonyi prefers the more explicit

```
$(document).ready(function() {...});
```

We should probably pick one and stick with it.

@cdelahousse @bheesham

**Comment by psimonyi** [comment]
The only reference I can find is this:
http://api.jquery.com/ready/

It doesn't mark $(handler) as "deprecated", like some others, but it is
pretty clearly an alternative syntax, not the primary one.

**Comment by spratt** [comment]
Christian agrees.  Going to consider this resolved.
