### ISSUE TITLE
SQL or NoSQL?

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#97]
I'm not sure we need the consistency guarantees of SQL.  Thoughts?

**Comment by psimonyi** [comment]
Zis is an issue ve should viscous.

**Comment by spratt** [comment]
Anil is pushing mongoDB, but I hear redis has seen a lot of adoption in industry: http://redis.io/

**Comment by spratt** [comment]
An old article on how to set up redis with node: http://howtonode.org/node-redis-fun

**Comment by spratt** [comment]
Apparently redis is good for scalability: http://stackoverflow.com/questions/4710420/scaling-node-js

**Comment by cdelahousse** [comment]
For the record, I want everyone to know that I think this is swell.
